name: ap_over_react
version: 1.0.0
authors:
  - Workiva Client Platform Team <cp@workiva.com>
  - Keal Jones
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  over_react: ^3.0.0-alpha
  react: ^5.0.0-alpha
dev_dependencies:
  test: ^1.5.2
  dart_dev: ^2.0.2
  dart_style: any
  build_resolvers: any
  build_runner: any
  build_test: any
  build_web_compilers: any
  over_react_test: ^2.5.1
  over_react_format:
    hosted:
      name: over_react_format
      url: https://pub.workiva.org
    version: ^2.1.2

dependency_overrides:
  over_react:
    git:
      url: https://github.com/Workiva/over_react.git
      ref: 3.1.0-wip
  react:
    git:
      url: https://github.com/cleandart/react-dart.git
      ref: 5.1.0-wip
  over_react_test:
    git:
      url: https://github.com/Workiva/over_react_test.git
      ref: react-16-wip
